### ISSUE TITLE
Performance drop when querying specific phrase on DuckDuckGo

### ISSUE THREAD

**Issue by mtekman** [saidinesh5/harbour-droplet#6]
Not sure if this constitutes as a proper issue, but I found it odd.

If you search for "guardian" or "guardian newspaper" in DuckDuckGo, the browser becomes unresponsive (due to I think it trying to render web thumbnails at the top of the page?)

All other queries appear to work fine.
(Also the browser is amazing!)

**Comment by saidinesh5** [comment]
Hi,

Yes, I have encountered similar issues too.. And there is not much I can do as this is the limitation of QtWebkit itself. I hope the move to QtWebEngine fixes this better. Will use this specific search as a test case then :)

**Comment by mtekman** [comment]
Ah gotcha. I'll close the issue and post to the right place, thanks
